# Generated by Django 3.2.13 on 2022-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
