# Generated by Django 3.2.13 on 2022-09-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20220915_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
